import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import styles from './Home.module.css';
import { FiGlobe, FiTrendingUp, FiShield, FiCompass, FiBox, FiShoppingBag, FiCoffee, FiHome } from 'react-icons/fi';
import heroImage from '../assets/hero-image.webp';
import { useLanguage } from '../LanguageContext';
const serviceIcons = [_jsx(FiGlobe, {}), _jsx(FiTrendingUp, {}), _jsx(FiShield, {}), _jsx(FiCompass, {})];
const industryIcons = [_jsx(FiCoffee, {}), _jsx(FiHome, {}), _jsx(FiShoppingBag, {}), _jsx(FiBox, {})];
const Home = () => {
    const { t } = useLanguage();
    return (_jsxs("div", { className: styles.home, children: [_jsxs("section", { className: styles.hero, children: [_jsx("img", { src: heroImage, alt: "Home hero", className: styles.heroImage, loading: "lazy", decoding: "async" }), _jsx("div", { className: styles.heroOverlay }), _jsxs("div", { className: styles.heroContent, children: [_jsx("p", { className: styles.eyebrow, children: t.home.eyebrow }), _jsx("h1", { className: styles.logo, children: t.home.heroTitle }), _jsx("p", { className: styles.tagline, children: t.home.heroTagline }), _jsxs("div", { className: styles.ctaGroup, children: [_jsx(Link, { to: "/services", className: styles.primaryCta, children: t.home.ctaPrimary }), _jsx(Link, { to: "/contact", className: styles.secondaryCta, children: t.home.ctaSecondary })] }), _jsxs("div", { className: styles.statsRow, children: [_jsxs("article", { children: [_jsx("h3", { children: t.home.stat1Val }), _jsx("p", { children: t.home.stat1Label })] }), _jsxs("article", { children: [_jsx("h3", { children: t.home.stat2Val }), _jsx("p", { children: t.home.stat2Label })] }), _jsxs("article", { children: [_jsx("h3", { children: t.home.stat3Val }), _jsx("p", { children: t.home.stat3Label })] })] })] })] }), _jsxs("section", { className: styles.section, children: [_jsxs("div", { className: styles.sectionHeader, children: [_jsx("h2", { children: t.home.servicesSectionTitle }), _jsx("p", { children: t.home.servicesSectionSubtitle })] }), _jsx("div", { className: styles.grid, children: t.home.services.map((service, index) => (_jsxs("div", { className: styles.card, children: [_jsx("div", { className: styles.iconWrapper, children: serviceIcons[index] }), _jsx("h3", { children: service.title }), _jsx("p", { children: service.description })] }, index))) })] }), _jsxs("section", { className: `${styles.section} ${styles.altSection}`, children: [_jsxs("div", { className: styles.sectionHeader, children: [_jsx("h2", { children: t.home.industriesSectionTitle }), _jsx("p", { children: t.home.industriesSectionSubtitle })] }), _jsx("div", { className: styles.grid, children: t.home.industries.map((industry, index) => (_jsxs("div", { className: styles.card, children: [_jsx("div", { className: styles.iconWrapper, children: industryIcons[index] }), _jsx("h3", { children: industry.title }), _jsx("p", { children: industry.description })] }, index))) })] }), _jsx("section", { className: styles.bottomCta, children: _jsxs("div", { className: styles.bottomInner, children: [_jsx("h2", { children: t.home.bottomTitle }), _jsx("p", { children: t.home.bottomText }), _jsx(Link, { to: "/contact", className: styles.primaryCta, children: t.home.bottomBtn })] }) })] }));
};
export default Home;
